# Generated by Django 5.1.7 on 2025-03-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('musique', 'Musique'), ('event', 'Event'), ('autre', 'Autre')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Emission',
        ),
    ]
